<?php

return [
    'AED' => [
        'name' => 'UAE Dirham',
        'code' => 784,
        'precision' => 2,
        'subunit' => 100,
        'symbol' => 'د.إ',
        'symbol_first' => true,
        'decimal_mark' => '.',
        'thousands_separator' => ',',
        'rate' => '',
    ],

    'AFN' => [
        'name' => 'Afghani',
        'code' => 971,
        'precision' => 2,
        'subunit' => 100,
        'symbol' => '؋',
        'symbol_first' => false,
        'decimal_mark' => '.',
        'thousands_separator' => ',',
        'rate' => '',
    ],

    'ALL' => [
        'name' => 'Lek',
        'code' => 8,
        'precision' => 2,
        'subunit' => 100,
        'symbol' => 'L',
        'symbol_first' => false,
        'decimal_mark' => '.',
        'thousands_separator' => ',',
        'rate' => '',
    ],

    'AMD' => [
        'name' => 'Armenian Dram',
        'code' => 51,
        'precision' => 2,
        'subunit' => 100,
        'symbol' => 'դր.',
        'symbol_first' => false,
        'decimal_mark' => '.',
        'thousands_separator' => ',',
        'rate' => '',
    ],

    'ANG' => [
        'name' => 'Netherlands Antillean Guilder',
        'code' => 532,
        'precision' => 2,
        'subunit' => 100,
        'symbol' => 'ƒ',
        'symbol_first' => true,
        'decimal_mark' => ',',
        'thousands_separator' => '.',
        'rate' => '',
    ],

    'AOA' => [
        'name' => 'Kwanza',
        'code' => 973,
        'precision' => 2,
        'subunit' => 100,
        'symbol' => 'Kz',
        'symbol_first' => false,
        'decimal_mark' => '.',
        'thousands_separator' => ',',
        'rate' => '',
    ],

    'ARS' => [
        'name' => 'Argentine Peso',
        'code' => 32,
        'precision' => 2,
        'subunit' => 100,
        'symbol' => '$',
        'symbol_first' => true,
        'decimal_mark' => ',',
        'thousands_separator' => '.',
        'rate' => '',
    ],

    'AUD' => [
        'name' => 'Australian Dollar',
        'code' => 36,
        'precision' => 2,
        'subunit' => 100,
        'symbol' => '$',
        'symbol_first' => true,
        'decimal_mark' => '.',
        'thousands_separator' => ' ',
        'rate' => '',
    ],

    'AWG' => [
        'name' => 'Aruban Florin',
        'code' => 533,
        'precision' => 2,
        'subunit' => 100,
        'symbol' => 'ƒ',
        'symbol_first' => false,
        'decimal_mark' => '.',
        'thousands_separator' => ',',
        'rate' => '',
    ],

    'AZN' => [
        'name' => 'Azerbaijanian Manat',
        'code' => 944,
        'precision' => 2,
        'subunit' => 100,
        'symbol' => '₼',
        'symbol_first' => true,
        'decimal_mark' => '.',
        'thousands_separator' => ',',
        'rate' => '',
    ],

    'BAM' => [
        'name' => 'Convertible Mark',
        'code' => 977,
        'precision' => 2,
        'subunit' => 100,
        'symbol' => 'КМ',
        'symbol_first' => true,
        'decimal_mark' => '.',
        'thousands_separator' => ',',
        'rate' => '',
    ],

    'BBD' => [
        'name' => 'Barbados Dollar',
        'code' => 52,
        'precision' => 2,
        'subunit' => 100,
        'symbol' => '$',
        'symbol_first' => false,
        'decimal_mark' => '.',
        'thousands_separator' => ',',
        'rate' => '',
    ],

    'BDT' => [
        'name' => 'Taka',
        'code' => 50,
        'precision' => 2,
        'subunit' => 100,
        'symbol' => '৳',
        'symbol_first' => true,
        'decimal_mark' => '.',
        'thousands_separator' => ',',
        'rate' => '',
    ],

    'BGN' => [
        'name' => 'Bulgarian Lev',
        'code' => 975,
        'precision' => 2,
        'subunit' => 100,
        'symbol' => 'лв',
        'symbol_first' => false,
        'decimal_mark' => '.',
        'thousands_separator' => ',',
        'rate' => '',
    ],

    'BHD' => [
        'name' => 'Bahraini Dinar',
        'code' => 48,
        'precision' => 3,
        'subunit' => 1000,
        'symbol' => 'ب.د',
        'symbol_first' => true,
        'decimal_mark' => '.',
        'thousands_separator' => ',',
        'rate' => '',
    ],

    'BIF' => [
        'name' => 'Burundi Franc',
        'code' => 108,
        'precision' => 0,
        'subunit' => 1,
        'symbol' => 'Fr',
        'symbol_first' => false,
        'decimal_mark' => '.',
        'thousands_separator' => ',',
        'rate' => '',
    ],

    'BMD' => [
        'name' => 'Bermudian Dollar',
        'code' => 60,
        'precision' => 2,
        'subunit' => 100,
        'symbol' => '$',
        'symbol_first' => true,
        'decimal_mark' => '.',
        'thousands_separator' => ',',
        'rate' => '',
    ],

    'BND' => [
        'name' => 'Brunei Dollar',
        'code' => 96,
        'precision' => 2,
        'subunit' => 100,
        'symbol' => '$',
        'symbol_first' => true,
        'decimal_mark' => '.',
        'thousands_separator' => ',',
        'rate' => '',
    ],

    'BOB' => [
        'name' => 'Boliviano',
        'code' => 68,
        'precision' => 2,
        'subunit' => 100,
        'symbol' => 'Bs.',
        'symbol_first' => true,
        'decimal_mark' => '.',
        'thousands_separator' => ',',
        'rate' => '',
    ],

    'BOV' => [
        'name' => 'Mvdol',
        'code' => 984,
        'precision' => 2,
        'subunit' => 100,
        'symbol' => 'Bs.',
        'symbol_first' => true,
        'decimal_mark' => '.',
        'thousands_separator' => ',',
        'rate' => '',
    ],

    'BRL' => [
        'name' => 'Brazilian Real',
        'code' => 986,
        'precision' => 2,
        'subunit' => 100,
        'symbol' => 'R$',
        'symbol_first' => true,
        'decimal_mark' => ',',
        'thousands_separator' => '.',
        'rate' => '',
    ],

    'BSD' => [
        'name' => 'Bahamian Dollar',
        'code' => 44,
        'precision' => 2,
        'subunit' => 100,
        'symbol' => '$',
        'symbol_first' => true,
        'decimal_mark' => '.',
        'thousands_separator' => ',',
        'rate' => '',
    ],

    'BTN' => [
        'name' => 'Ngultrum',
        'code' => 64,
        'precision' => 2,
        'subunit' => 100,
        'symbol' => 'Nu.',
        'symbol_first' => false,
        'decimal_mark' => '.',
        'thousands_separator' => ',',
        'rate' => '',
    ],

    'BWP' => [
        'name' => 'Pula',
        'code' => 72,
        'precision' => 2,
        'subunit' => 100,
        'symbol' => 'P',
        'symbol_first' => true,
        'decimal_mark' => '.',
        'thousands_separator' => ',',
        'rate' => '',
    ],

    'BYR' => [
        'name' => 'Belarussian Ruble',
        'code' => 974,
        'precision' => 0,
        'subunit' => 1,
        'symbol' => 'Br',
        'symbol_first' => false,
        'decimal_mark' => ',',
        'thousands_separator' => ' ',
        'rate' => '',
    ],

    'BZD' => [
        'name' => 'Belize Dollar',
        'code' => 84,
        'precision' => 2,
        'subunit' => 100,
        'symbol' => '$',
        'symbol_first' => true,
        'decimal_mark' => '.',
        'thousands_separator' => ',',
        'rate' => '',
    ],

    'CAD' => [
        'name' => 'Canadian Dollar',
        'code' => 124,
        'precision' => 2,
        'subunit' => 100,
        'symbol' => '$',
        'symbol_first' => true,
        'decimal_mark' => '.',
        'thousands_separator' => ',',
        'rate' => '',
    ],

    'CDF' => [
        'name' => 'Congolese Franc',
        'code' => 976,
        'precision' => 2,
        'subunit' => 100,
        'symbol' => 'Fr',
        'symbol_first' => false,
        'decimal_mark' => '.',
        'thousands_separator' => ',',
        'rate' => '',
    ],

    'CHF' => [
        'name' => 'Swiss Franc',
        'code' => 756,
        'precision' => 2,
        'subunit' => 100,
        'symbol' => 'CHF',
        'symbol_first' => true,
        'decimal_mark' => '.',
        'thousands_separator' => ',',
        'rate' => '',
    ],

    'CLF' => [
        'name' => 'Unidades de fomento',
        'code' => 990,
        'precision' => 0,
        'subunit' => 1,
        'symbol' => 'UF',
        'symbol_first' => true,
        'decimal_mark' => ',',
        'thousands_separator' => '.',
        'rate' => '',
    ],

    'CLP' => [
        'name' => 'Chilean Peso',
        'code' => 152,
        'precision' => 0,
        'subunit' => 1,
        'symbol' => '$',
        'symbol_first' => true,
        'decimal_mark' => ',',
        'thousands_separator' => '.',
        'rate' => '',
    ],

    'CNY' => [
        'name' => 'Yuan Renminbi',
        'code' => 156,
        'precision' => 2,
        'subunit' => 100,
        'symbol' => '¥',
        'symbol_first' => true,
        'decimal_mark' => '.',
        'thousands_separator' => ',',
        'rate' => '',
    ],

    'COP' => [
        'name' => 'Colombian Peso',
        'code' => 170,
        'precision' => 2,
        'subunit' => 100,
        'symbol' => '$',
        'symbol_first' => true,
        'decimal_mark' => ',',
        'thousands_separator' => '.',
        'rate' => '',
    ],

    'CRC' => [
        'name' => 'Costa Rican Colon',
        'code' => 188,
        'precision' => 2,
        'subunit' => 100,
        'symbol' => '₡',
        'symbol_first' => true,
        'decimal_mark' => ',',
        'thousands_separator' => '.',
        'rate' => '',
    ],

    'CUC' => [
        'name' => 'Peso Convertible',
        'code' => 931,
        'precision' => 2,
        'subunit' => 100,
        'symbol' => '$',
        'symbol_first' => false,
        'decimal_mark' => '.',
        'thousands_separator' => ',',
        'rate' => '',
    ],

    'CUP' => [
        'name' => 'Cuban Peso',
        'code' => 192,
        'precision' => 2,
        'subunit' => 100,
        'symbol' => '$',
        'symbol_first' => true,
        'decimal_mark' => '.',
        'thousands_separator' => ',',
        'rate' => '',
    ],

    'CVE' => [
        'name' => 'Cape Verde Escudo',
        'code' => 132,
        'precision' => 2,
        'subunit' => 100,
        'symbol' => '$',
        'symbol_first' => false,
        'decimal_mark' => '.',
        'thousands_separator' => ',',
        'rate' => '',
    ],

    'CZK' => [
        'name' => 'Czech Koruna',
        'code' => 203,
        'precision' => 2,
        'subunit' => 100,
        'symbol' => 'Kč',
        'symbol_first' => false,
        'decimal_mark' => ',',
        'thousands_separator' => '.',
        'rate' => '',
    ],

    'DJF' => [
        'name' => 'Djibouti Franc',
        'code' => 262,
        'precision' => 0,
        'subunit' => 1,
        'symbol' => 'Fdj',
        'symbol_first' => false,
        'decimal_mark' => '.',
        'thousands_separator' => ',',
        'rate' => '',
    ],

    'DKK' => [
        'name' => 'Danish Krone',
        'code' => 208,
        'precision' => 2,
        'subunit' => 100,
        'symbol' => 'kr',
        'symbol_first' => false,
        'decimal_mark' => ',',
        'thousands_separator' => '.',
        'rate' => '',
    ],

    'DOP' => [
        'name' => 'Dominican Peso',
        'code' => 214,
        'precision' => 2,
        'subunit' => 100,
        'symbol' => '$',
        'symbol_first' => true,
        'decimal_mark' => '.',
        'thousands_separator' => ',',
        'rate' => '',
    ],

    'DZD' => [
        'name' => 'Algerian Dinar',
        'code' => 12,
        'precision' => 2,
        'subunit' => 100,
        'symbol' => 'د.ج',
        'symbol_first' => false,
        'decimal_mark' => '.',
        'thousands_separator' => ',',
        'rate' => '',
    ],

    'EGP' => [
        'name' => 'Egyptian Pound',
        'code' => 818,
        'precision' => 2,
        'subunit' => 100,
        'symbol' => 'ج.م',
        'symbol_first' => true,
        'decimal_mark' => '.',
        'thousands_separator' => ',',
        'rate' => '',
    ],

    'ERN' => [
        'name' => 'Nakfa',
        'code' => 232,
        'precision' => 2,
        'subunit' => 100,
        'symbol' => 'Nfk',
        'symbol_first' => false,
        'decimal_mark' => '.',
        'thousands_separator' => ',',
        'rate' => '',
    ],

    'ETB' => [
        'name' => 'Ethiopian Birr',
        'code' => 230,
        'precision' => 2,
        'subunit' => 100,
        'symbol' => 'Br',
        'symbol_first' => false,
        'decimal_mark' => '.',
        'thousands_separator' => ',',
        'rate' => '',
    ],

    'EUR' => [
        'name' => 'Euro',
        'code' => 978,
        'precision' => 2,
        'subunit' => 100,
        'symbol' => '€',
        'symbol_first' => true,
        'decimal_mark' => ',',
        'thousands_separator' => '.',
        'rate' => '',
    ],

    'FJD' => [
        'name' => 'Fiji Dollar',
        'code' => 242,
        'precision' => 2,
        'subunit' => 100,
        'symbol' => '$',
        'symbol_first' => false,
        'decimal_mark' => '.',
        'thousands_separator' => ',',
        'rate' => '',
    ],

    'FKP' => [
        'name' => 'Falkland Islands Pound',
        'code' => 238,
        'precision' => 2,
        'subunit' => 100,
        'symbol' => '£',
        'symbol_first' => false,
        'decimal_mark' => '.',
        'thousands_separator' => ',',
        'rate' => '',
    ],

    'GBP' => [
        'name' => 'Pound Sterling',
        'code' => 826,
        'precision' => 2,
        'subunit' => 100,
        'symbol' => '£',
        'symbol_first' => true,
        'decimal_mark' => '.',
        'thousands_separator' => ',',
        'rate' => '',
    ],

    'GEL' => [
        'name' => 'Lari',
        'code' => 981,
        'precision' => 2,
        'subunit' => 100,
        'symbol' => 'ლ',
        'symbol_first' => false,
        'decimal_mark' => '.',
        'thousands_separator' => ',',
        'rate' => '',
    ],

    'GHS' => [
        'name' => 'Ghana Cedi',
        'code' => 936,
        'precision' => 2,
        'subunit' => 100,
        'symbol' => '₵',
        'symbol_first' => true,
        'decimal_mark' => '.',
        'thousands_separator' => ',',
        'rate' => '',
    ],

    'GIP' => [
        'name' => 'Gibraltar Pound',
        'code' => 292,
        'precision' => 2,
        'subunit' => 100,
        'symbol' => '£',
        'symbol_first' => true,
        'decimal_mark' => '.',
        'thousands_separator' => ',',
        'rate' => '',
    ],

    'GMD' => [
        'name' => 'Dalasi',
        'code' => 270,
        'precision' => 2,
        'subunit' => 100,
        'symbol' => 'D',
        'symbol_first' => false,
        'decimal_mark' => '.',
        'thousands_separator' => ',',
        'rate' => '',
    ],

    'GNF' => [
        'name' => 'Guinea Franc',
        'code' => 324,
        'precision' => 0,
        'subunit' => 1,
        'symbol' => 'Fr',
        'symbol_first' => false,
        'decimal_mark' => '.',
        'thousands_separator' => ',',
        'rate' => '',
    ],

    'GTQ' => [
        'name' => 'Quetzal',
        'code' => 320,
        'precision' => 2,
        'subunit' => 100,
        'symbol' => 'Q',
        'symbol_first' => true,
        'decimal_mark' => '.',
        'thousands_separator' => ',',
        'rate' => '',
    ],

    'GYD' => [
        'name' => 'Guyana Dollar',
        'code' => 328,
        'precision' => 2,
        'subunit' => 100,
        'symbol' => '$',
        'symbol_first' => false,
        'decimal_mark' => '.',
        'thousands_separator' => ',',
        'rate' => '',
    ],

    'HKD' => [
        'name' => 'Hong Kong Dollar',
        'code' => 344,
        'precision' => 2,
        'subunit' => 100,
        'symbol' => '$',
        'symbol_first' => true,
        'decimal_mark' => '.',
        'thousands_separator' => ',',
        'rate' => '',
    ],

    'HNL' => [
        'name' => 'Lempira',
        'code' => 340,
        'precision' => 2,
        'subunit' => 100,
        'symbol' => 'L',
        'symbol_first' => true,
        'decimal_mark' => '.',
        'thousands_separator' => ',',
        'rate' => '',
    ],

    'HRK' => [
        'name' => 'Croatian Kuna',
        'code' => 191,
        'precision' => 2,
        'subunit' => 100,
        'symbol' => 'kn',
        'symbol_first' => true,
        'decimal_mark' => ',',
        'thousands_separator' => '.',
        'rate' => '',
    ],

    'HTG' => [
        'name' => 'Gourde',
        'code' => 332,
        'precision' => 2,
        'subunit' => 100,
        'symbol' => 'G',
        'symbol_first' => false,
        'decimal_mark' => '.',
        'thousands_separator' => ',',
        'rate' => '',
    ],

    'HUF' => [
        'name' => 'Forint',
        'code' => 348,
        'precision' => 2,
        'subunit' => 100,
        'symbol' => 'Ft',
        'symbol_first' => false,
        'decimal_mark' => ',',
        'thousands_separator' => '.',
        'rate' => '',
    ],

    'IDR' => [
        'name' => 'Rupiah',
        'code' => 360,
        'precision' => 2,
        'subunit' => 100,
        'symbol' => 'Rp',
        'symbol_first' => true,
        'decimal_mark' => ',',
        'thousands_separator' => '.',
        'rate' => '',
    ],

    'ILS' => [
        'name' => 'New Israeli Sheqel',
        'code' => 376,
        'precision' => 2,
        'subunit' => 100,
        'symbol' => '₪',
        'symbol_first' => true,
        'decimal_mark' => '.',
        'thousands_separator' => ',',
        'rate' => '',
    ],

    'INR' => [
        'name' => 'Indian Rupee',
        'code' => 356,
        'precision' => 2,
        'subunit' => 100,
        'symbol' => '₹',
        'symbol_first' => true,
        'decimal_mark' => '.',
        'thousands_separator' => ',',
        'rate' => '',
    ],

    'IQD' => [
        'name' => 'Iraqi Dinar',
        'code' => 368,
        'precision' => 3,
        'subunit' => 1000,
        'symbol' => 'ع.د',
        'symbol_first' => false,
        'decimal_mark' => '.',
        'thousands_separator' => ',',
        'rate' => '',
    ],

    'IRR' => [
        'name' => 'Iranian Rial',
        'code' => 364,
        'precision' => 2,
        'subunit' => 100,
        'symbol' => '﷼',
        'symbol_first' => true,
        'decimal_mark' => '.',
        'thousands_separator' => ',',
        'rate' => '',
    ],

    'ISK' => [
        'name' => 'Iceland Krona',
        'code' => 352,
        'precision' => 0,
        'subunit' => 1,
        'symbol' => 'kr',
        'symbol_first' => true,
        'decimal_mark' => ',',
        'thousands_separator' => '.',
        'rate' => '',
    ],

    'JMD' => [
        'name' => 'Jamaican Dollar',
        'code' => 388,
        'precision' => 2,
        'subunit' => 100,
        'symbol' => '$',
        'symbol_first' => true,
        'decimal_mark' => '.',
        'thousands_separator' => ',',
        'rate' => '',
    ],

    'JOD' => [
        'name' => 'Jordanian Dinar',
        'code' => 400,
        'precision' => 3,
        'subunit' => 100,
        'symbol' => 'د.ا',
        'symbol_first' => true,
        'decimal_mark' => '.',
        'thousands_separator' => ',',
        'rate' => '',
    ],

    'JPY' => [
        'name' => 'Yen',
        'code' => 392,
        'precision' => 0,
        'subunit' => 1,
        'symbol' => '¥',
        'symbol_first' => true,
        'decimal_mark' => '.',
        'thousands_separator' => ',',
        'rate' => '',
    ],

    'KES' => [
        'name' => 'Kenyan Shilling',
        'code' => 404,
        'precision' => 2,
        'subunit' => 100,
        'symbol' => 'KSh',
        'symbol_first' => true,
        'decimal_mark' => '.',
        'thousands_separator' => ',',
        'rate' => '',
    ],

    'KGS' => [
        'name' => 'Som',
        'code' => 417,
        'precision' => 2,
        'subunit' => 100,
        'symbol' => 'som',
        'symbol_first' => false,
        'decimal_mark' => '.',
        'thousands_separator' => ',',
        'rate' => '',
    ],

    'KHR' => [
        'name' => 'Riel',
        'code' => 116,
        'precision' => 2,
        'subunit' => 100,
        'symbol' => '៛',
        'symbol_first' => false,
        'decimal_mark' => '.',
        'thousands_separator' => ',',
        'rate' => '',
    ],

    'KMF' => [
        'name' => 'Comoro Franc',
        'code' => 174,
        'precision' => 0,
        'subunit' => 1,
        'symbol' => 'Fr',
        'symbol_first' => false,
        'decimal_mark' => '.',
        'thousands_separator' => ',',
        'rate' => '',
    ],

    'KPW' => [
        'name' => 'North Korean Won',
        'code' => 408,
        'precision' => 2,
        'subunit' => 100,
        'symbol' => '₩',
        'symbol_first' => false,
        'decimal_mark' => '.',
        'thousands_separator' => ',',
        'rate' => '',
    ],

    'KRW' => [
        'name' => 'Won',
        'code' => 410,
        'precision' => 0,
        'subunit' => 1,
        'symbol' => '₩',
        'symbol_first' => true,
        'decimal_mark' => '.',
        'thousands_separator' => ',',
        'rate' => '',
    ],

    'KWD' => [
        'name' => 'Kuwaiti Dinar',
        'code' => 414,
        'precision' => 3,
        'subunit' => 1000,
        'symbol' => 'د.ك',
        'symbol_first' => true,
        'decimal_mark' => '.',
        'thousands_separator' => ',',
        'rate' => '',
    ],

    'KYD' => [
        'name' => 'Cayman Islands Dollar',
        'code' => 136,
        'precision' => 2,
        'subunit' => 100,
        'symbol' => '$',
        'symbol_first' => true,
        'decimal_mark' => '.',
        'thousands_separator' => ',',
        'rate' => '',
    ],

    'KZT' => [
        'name' => 'Tenge',
        'code' => 398,
        'precision' => 2,
        'subunit' => 100,
        'symbol' => '〒',
        'symbol_first' => false,
        'decimal_mark' => '.',
        'thousands_separator' => ',',
        'rate' => '',
    ],

    'LAK' => [
        'name' => 'Kip',
        'code' => 418,
        'precision' => 2,
        'subunit' => 100,
        'symbol' => '₭',
        'symbol_first' => false,
        'decimal_mark' => '.',
        'thousands_separator' => ',',
        'rate' => '',
    ],

    'LBP' => [
        'name' => 'Lebanese Pound',
        'code' => 422,
        'precision' => 2,
        'subunit' => 100,
        'symbol' => 'ل.ل',
        'symbol_first' => true,
        'decimal_mark' => '.',
        'thousands_separator' => ',',
        'rate' => '',
    ],

    'LKR' => [
        'name' => 'Sri Lanka Rupee',
        'code' => 144,
        'precision' => 2,
        'subunit' => 100,
        'symbol' => '₨',
        'symbol_first' => false,
        'decimal_mark' => '.',
        'thousands_separator' => ',',
        'rate' => '',
    ],

    'LRD' => [
        'name' => 'Liberian Dollar',
        'code' => 430,
        'precision' => 2,
        'subunit' => 100,
        'symbol' => '$',
        'symbol_first' => false,
        'decimal_mark' => '.',
        'thousands_separator' => ',',
        'rate' => '',
    ],

    'LSL' => [
        'name' => 'Loti',
        'code' => 426,
        'precision' => 2,
        'subunit' => 100,
        'symbol' => 'L',
        'symbol_first' => false,
        'decimal_mark' => '.',
        'thousands_separator' => ',',
        'rate' => '',
    ],

    'LTL' => [
        'name' => 'Lithuanian Litas',
        'code' => 440,
        'precision' => 2,
        'subunit' => 100,
        'symbol' => 'Lt',
        'symbol_first' => false,
        'decimal_mark' => '.',
        'thousands_separator' => ',',
        'rate' => '',
    ],

    'LVL' => [
        'name' => 'Latvian Lats',
        'code' => 428,
        'precision' => 2,
        'subunit' => 100,
        'symbol' => 'Ls',
        'symbol_first' => true,
        'decimal_mark' => '.',
        'thousands_separator' => ',',
        'rate' => '',
    ],

    'LYD' => [
        'name' => 'Libyan Dinar',
        'code' => 434,
        'precision' => 3,
        'subunit' => 1000,
        'symbol' => 'ل.د',
        'symbol_first' => false,
        'decimal_mark' => '.',
        'thousands_separator' => ',',
        'rate' => '',
    ],

    'MAD' => [
        'name' => 'Moroccan Dirham',
        'code' => 504,
        'precision' => 2,
        'subunit' => 100,
        'symbol' => 'د.م.',
        'symbol_first' => false,
        'decimal_mark' => '.',
        'thousands_separator' => ',',
        'rate' => '',
    ],

    'MDL' => [
        'name' => 'Moldovan Leu',
        'code' => 498,
        'precision' => 2,
        'subunit' => 100,
        'symbol' => 'L',
        'symbol_first' => false,
        'decimal_mark' => '.',
        'thousands_separator' => ',',
        'rate' => '',
    ],

    'MGA' => [
        'name' => 'Malagasy Ariary',
        'code' => 969,
        'precision' => 2,
        'subunit' => 5,
        'symbol' => 'Ar',
        'symbol_first' => true,
        'decimal_mark' => '.',
        'thousands_separator' => ',',
        'rate' => '',
    ],

    'MKD' => [
        'name' => 'Denar',
        'code' => 807,
        'precision' => 2,
        'subunit' => 100,
        'symbol' => 'ден',
        'symbol_first' => false,
        'decimal_mark' => '.',
        'thousands_separator' => ',',
        'rate' => '',
    ],

    'MMK' => [
        'name' => 'Kyat',
        'code' => 104,
        'precision' => 2,
        'subunit' => 100,
        'symbol' => 'K',
        'symbol_first' => false,
        'decimal_mark' => '.',
        'thousands_separator' => ',',
        'rate' => '',
    ],

    'MNT' => [
        'name' => 'Tugrik',
        'code' => 496,
        'precision' => 2,
        'subunit' => 100,
        'symbol' => '₮',
        'symbol_first' => false,
        'decimal_mark' => '.',
        'thousands_separator' => ',',
        'rate' => '',
    ],

    'MOP' => [
        'name' => 'Pataca',
        'code' => 446,
        'precision' => 2,
        'subunit' => 100,
        'symbol' => 'P',
        'symbol_first' => false,
        'decimal_mark' => '.',
        'thousands_separator' => ',',
        'rate' => '',
    ],

    'MRO' => [
        'name' => 'Ouguiya',
        'code' => 478,
        'precision' => 2,
        'subunit' => 5,
        'symbol' => 'UM',
        'symbol_first' => false,
        'decimal_mark' => '.',
        'thousands_separator' => ',',
        'rate' => '',
    ],

    'MUR' => [
        'name' => 'Mauritius Rupee',
        'code' => 480,
        'precision' => 2,
        'subunit' => 100,
        'symbol' => '₨',
        'symbol_first' => true,
        'decimal_mark' => '.',
        'thousands_separator' => ',',
        'rate' => '',
    ],

    'MVR' => [
        'name' => 'Rufiyaa',
        'code' => 462,
        'precision' => 2,
        'subunit' => 100,
        'symbol' => 'MVR',
        'symbol_first' => false,
        'decimal_mark' => '.',
        'thousands_separator' => ',',
        'rate' => '',
    ],

    'MWK' => [
        'name' => 'Kwacha',
        'code' => 454,
        'precision' => 2,
        'subunit' => 100,
        'symbol' => 'MK',
        'symbol_first' => false,
        'decimal_mark' => '.',
        'thousands_separator' => ',',
        'rate' => '',
    ],

    'MXN' => [
        'name' => 'Mexican Peso',
        'code' => 484,
        'precision' => 2,
        'subunit' => 100,
        'symbol' => '$',
        'symbol_first' => true,
        'decimal_mark' => '.',
        'thousands_separator' => ',',
        'rate' => '',
    ],

    'MYR' => [
        'name' => 'Malaysian Ringgit',
        'code' => 458,
        'precision' => 2,
        'subunit' => 100,
        'symbol' => 'RM',
        'symbol_first' => true,
        'decimal_mark' => '.',
        'thousands_separator' => ',',
        'rate' => '',
    ],

    'MZN' => [
        'name' => 'Mozambique Metical',
        'code' => 943,
        'precision' => 2,
        'subunit' => 100,
        'symbol' => 'MTn',
        'symbol_first' => true,
        'decimal_mark' => ',',
        'thousands_separator' => '.',
        'rate' => '',
    ],

    'NAD' => [
        'name' => 'Namibia Dollar',
        'code' => 516,
        'precision' => 2,
        'subunit' => 100,
        'symbol' => '$',
        'symbol_first' => false,
        'decimal_mark' => '.',
        'thousands_separator' => ',',
        'rate' => '',
    ],

    'NGN' => [
        'name' => 'Naira',
        'code' => 566,
        'precision' => 2,
        'subunit' => 100,
        'symbol' => '₦',
        'symbol_first' => true,
        'decimal_mark' => '.',
        'thousands_separator' => ',',
        'rate' => '',
    ],

    'NIO' => [
        'name' => 'Cordoba Oro',
        'code' => 558,
        'precision' => 2,
        'subunit' => 100,
        'symbol' => 'C$',
        'symbol_first' => false,
        'decimal_mark' => '.',
        'thousands_separator' => ',',
        'rate' => '',
    ],

    'NOK' => [
        'name' => 'Norwegian Krone',
        'code' => 578,
        'precision' => 2,
        'subunit' => 100,
        'symbol' => 'kr',
        'symbol_first' => false,
        'decimal_mark' => ',',
        'thousands_separator' => '.',
        'rate' => '',
    ],

    'NPR' => [
        'name' => 'Nepalese Rupee',
        'code' => 524,
        'precision' => 2,
        'subunit' => 100,
        'symbol' => '₨',
        'symbol_first' => true,
        'decimal_mark' => '.',
        'thousands_separator' => ',',
        'rate' => '',
    ],

    'NZD' => [
        'name' => 'New Zealand Dollar',
        'code' => 554,
        'precision' => 2,
        'subunit' => 100,
        'symbol' => '$',
        'symbol_first' => true,
        'decimal_mark' => '.',
        'thousands_separator' => ',',
        'rate' => '',
    ],

    'OMR' => [
        'name' => 'Rial Omani',
        'code' => 512,
        'precision' => 3,
        'subunit' => 1000,
        'symbol' => 'ر.ع.',
        'symbol_first' => true,
        'decimal_mark' => '.',
        'thousands_separator' => ',',
        'rate' => '',
    ],

    'PAB' => [
        'name' => 'Balboa',
        'code' => 590,
        'precision' => 2,
        'subunit' => 100,
        'symbol' => 'B/.',
        'symbol_first' => false,
        'decimal_mark' => '.',
        'thousands_separator' => ',',
        'rate' => '',
    ],

    'PEN' => [
        'name' => 'Nuevo Sol',
        'code' => 604,
        'precision' => 2,
        'subunit' => 100,
        'symbol' => 'S/.',
        'symbol_first' => true,
        'decimal_mark' => '.',
        'thousands_separator' => ',',
        'rate' => '',
    ],

    'PGK' => [
        'name' => 'Kina',
        'code' => 598,
        'precision' => 2,
        'subunit' => 100,
        'symbol' => 'K',
        'symbol_first' => false,
        'decimal_mark' => '.',
        'thousands_separator' => ',',
        'rate' => '',
    ],

    'PHP' => [
        'name' => 'Philippine Peso',
        'code' => 608,
        'precision' => 2,
        'subunit' => 100,
        'symbol' => '₱',
        'symbol_first' => true,
        'decimal_mark' => '.',
        'thousands_separator' => ',',
        'rate' => '',
    ],

    'PKR' => [
        'name' => 'Pakistan Rupee',
        'code' => 586,
        'precision' => 2,
        'subunit' => 100,
        'symbol' => '₨',
        'symbol_first' => true,
        'decimal_mark' => '.',
        'thousands_separator' => ',',
        'rate' => '',
    ],

    'PLN' => [
        'name' => 'Zloty',
        'code' => 985,
        'precision' => 2,
        'subunit' => 100,
        'symbol' => 'zł',
        'symbol_first' => false,
        'decimal_mark' => ',',
        'thousands_separator' => ' ',
        'rate' => '',
    ],

    'PYG' => [
        'name' => 'Guarani',
        'code' => 600,
        'precision' => 0,
        'subunit' => 1,
        'symbol' => '₲',
        'symbol_first' => true,
        'decimal_mark' => '.',
        'thousands_separator' => ',',
        'rate' => '',
    ],

    'QAR' => [
        'name' => 'Qatari Rial',
        'code' => 634,
        'precision' => 2,
        'subunit' => 100,
        'symbol' => 'ر.ق',
        'symbol_first' => false,
        'decimal_mark' => '.',
        'thousands_separator' => ',',
        'rate' => '',
    ],

    'RON' => [
        'name' => 'New Romanian Leu',
        'code' => 946,
        'precision' => 2,
        'subunit' => 100,
        'symbol' => 'Lei',
        'symbol_first' => true,
        'decimal_mark' => ',',
        'thousands_separator' => '.',
        'rate' => '',
    ],

    'RSD' => [
        'name' => 'Serbian Dinar',
        'code' => 941,
        'precision' => 2,
        'subunit' => 100,
        'symbol' => 'РСД',
        'symbol_first' => true,
        'decimal_mark' => '.',
        'thousands_separator' => ',',
        'rate' => '',
    ],

    'RUB' => [
        'name' => 'Russian Ruble',
        'code' => 643,
        'precision' => 2,
        'subunit' => 100,
        'symbol' => '₽',
        'symbol_first' => false,
        'decimal_mark' => ',',
        'thousands_separator' => '.',
        'rate' => '',
    ],

    'RWF' => [
        'name' => 'Rwanda Franc',
        'code' => 646,
        'precision' => 0,
        'subunit' => 1,
        'symbol' => 'FRw',
        'symbol_first' => false,
        'decimal_mark' => '.',
        'thousands_separator' => ',',
        'rate' => '',
    ],

    'SAR' => [
        'name' => 'Saudi Riyal',
        'code' => 682,
        'precision' => 2,
        'subunit' => 100,
        'symbol' => 'ر.س',
        'symbol_first' => true,
        'decimal_mark' => '.',
        'thousands_separator' => ',',
        'rate' => '',
    ],

    'SBD' => [
        'name' => 'Solomon Islands Dollar',
        'code' => 90,
        'precision' => 2,
        'subunit' => 100,
        'symbol' => '$',
        'symbol_first' => false,
        'decimal_mark' => '.',
        'thousands_separator' => ',',
        'rate' => '',
    ],

    'SCR' => [
        'name' => 'Seychelles Rupee',
        'code' => 690,
        'precision' => 2,
        'subunit' => 100,
        'symbol' => '₨',
        'symbol_first' => false,
        'decimal_mark' => '.',
        'thousands_separator' => ',',
        'rate' => '',
    ],

    'SDG' => [
        'name' => 'Sudanese Pound',
        'code' => 938,
        'precision' => 2,
        'subunit' => 100,
        'symbol' => '£',
        'symbol_first' => true,
        'decimal_mark' => '.',
        'thousands_separator' => ',',
        'rate' => '',
    ],

    'SEK' => [
        'name' => 'Swedish Krona',
        'code' => 752,
        'precision' => 2,
        'subunit' => 100,
        'symbol' => 'kr',
        'symbol_first' => false,
        'decimal_mark' => ',',
        'thousands_separator' => ' ',
        'rate' => '',
    ],

    'SGD' => [
        'name' => 'Singapore Dollar',
        'code' => 702,
        'precision' => 2,
        'subunit' => 100,
        'symbol' => '$',
        'symbol_first' => true,
        'decimal_mark' => '.',
        'thousands_separator' => ',',
        'rate' => '',
    ],

    'SHP' => [
        'name' => 'Saint Helena Pound',
        'code' => 654,
        'precision' => 2,
        'subunit' => 100,
        'symbol' => '£',
        'symbol_first' => false,
        'decimal_mark' => '.',
        'thousands_separator' => ',',
        'rate' => '',
    ],

    'SLL' => [
        'name' => 'Leone',
        'code' => 694,
        'precision' => 2,
        'subunit' => 100,
        'symbol' => 'Le',
        'symbol_first' => false,
        'decimal_mark' => '.',
        'thousands_separator' => ',',
        'rate' => '',
    ],

    'SOS' => [
        'name' => 'Somali Shilling',
        'code' => 706,
        'precision' => 2,
        'subunit' => 100,
        'symbol' => 'Sh',
        'symbol_first' => false,
        'decimal_mark' => '.',
        'thousands_separator' => ',',
        'rate' => '',
    ],

    'SRD' => [
        'name' => 'Surinam Dollar',
        'code' => 968,
        'precision' => 2,
        'subunit' => 100,
        'symbol' => '$',
        'symbol_first' => false,
        'decimal_mark' => '.',
        'thousands_separator' => ',',
        'rate' => '',
    ],

    'SSP' => [
        'name' => 'South Sudanese Pound',
        'code' => 728,
        'precision' => 2,
        'subunit' => 100,
        'symbol' => '£',
        'symbol_first' => false,
        'decimal_mark' => '.',
        'thousands_separator' => ',',
        'rate' => '',
    ],

    'STD' => [
        'name' => 'Dobra',
        'code' => 678,
        'precision' => 2,
        'subunit' => 100,
        'symbol' => 'Db',
        'symbol_first' => false,
        'decimal_mark' => '.',
        'thousands_separator' => ',',
        'rate' => '',
    ],

    'SVC' => [
        'name' => 'El Salvador Colon',
        'code' => 222,
        'precision' => 2,
        'subunit' => 100,
        'symbol' => '₡',
        'symbol_first' => true,
        'decimal_mark' => '.',
        'thousands_separator' => ',',
        'rate' => '',
    ],

    'SYP' => [
        'name' => 'Syrian Pound',
        'code' => 760,
        'precision' => 2,
        'subunit' => 100,
        'symbol' => '£S',
        'symbol_first' => false,
        'decimal_mark' => '.',
        'thousands_separator' => ',',
        'rate' => '',
    ],

    'SZL' => [
        'name' => 'Lilangeni',
        'code' => 748,
        'precision' => 2,
        'subunit' => 100,
        'symbol' => 'E',
        'symbol_first' => true,
        'decimal_mark' => '.',
        'thousands_separator' => ',',
        'rate' => '',
    ],

    'THB' => [
        'name' => 'Baht',
        'code' => 764,
        'precision' => 2,
        'subunit' => 100,
        'symbol' => '฿',
        'symbol_first' => true,
        'decimal_mark' => '.',
        'thousands_separator' => ',',
        'rate' => '',
    ],

    'TJS' => [
        'name' => 'Somoni',
        'code' => 972,
        'precision' => 2,
        'subunit' => 100,
        'symbol' => 'ЅМ',
        'symbol_first' => false,
        'decimal_mark' => '.',
        'thousands_separator' => ',',
        'rate' => '',
    ],

    'TMT' => [
        'name' => 'Turkmenistan New Manat',
        'code' => 934,
        'precision' => 2,
        'subunit' => 100,
        'symbol' => 'T',
        'symbol_first' => false,
        'decimal_mark' => '.',
        'thousands_separator' => ',',
        'rate' => '',
    ],

    'TND' => [
        'name' => 'Tunisian Dinar',
        'code' => 788,
        'precision' => 3,
        'subunit' => 1000,
        'symbol' => 'د.ت',
        'symbol_first' => false,
        'decimal_mark' => '.',
        'thousands_separator' => ',',
        'rate' => '',
    ],

    'TOP' => [
        'name' => 'Pa’anga',
        'code' => 776,
        'precision' => 2,
        'subunit' => 100,
        'symbol' => 'T$',
        'symbol_first' => true,
        'decimal_mark' => '.',
        'thousands_separator' => ',',
        'rate' => '',
    ],

    'TRY' => [
        'name' => 'Turkish Lira',
        'code' => 949,
        'precision' => 2,
        'subunit' => 100,
        'symbol' => '₺',
        'symbol_first' => true,
        'decimal_mark' => ',',
        'thousands_separator' => '.',
        'rate' => '',
    ],

    'TTD' => [
        'name' => 'Trinidad and Tobago Dollar',
        'code' => 780,
        'precision' => 2,
        'subunit' => 100,
        'symbol' => '$',
        'symbol_first' => false,
        'decimal_mark' => '.',
        'thousands_separator' => ',',
        'rate' => '',
    ],

    'TWD' => [
        'name' => 'New Taiwan Dollar',
        'code' => 901,
        'precision' => 2,
        'subunit' => 100,
        'symbol' => '$',
        'symbol_first' => true,
        'decimal_mark' => '.',
        'thousands_separator' => ',',
        'rate' => '',
    ],

    'TZS' => [
        'name' => 'Tanzanian Shilling',
        'code' => 834,
        'precision' => 2,
        'subunit' => 100,
        'symbol' => 'Sh',
        'symbol_first' => true,
        'decimal_mark' => '.',
        'thousands_separator' => ',',
        'rate' => '',
    ],

    'UAH' => [
        'name' => 'Hryvnia',
        'code' => 980,
        'precision' => 2,
        'subunit' => 100,
        'symbol' => '₴',
        'symbol_first' => false,
        'decimal_mark' => '.',
        'thousands_separator' => ',',
        'rate' => '',
    ],

    'UGX' => [
        'name' => 'Uganda Shilling',
        'code' => 800,
        'precision' => 0,
        'subunit' => 1,
        'symbol' => 'USh',
        'symbol_first' => false,
        'decimal_mark' => '.',
        'thousands_separator' => ',',
        'rate' => '',
    ],

    'USD' => [
        'name' => 'US Dollar',
        'code' => 840,
        'precision' => 2,
        'subunit' => 100,
        'symbol' => '$',
        'symbol_first' => true,
        'decimal_mark' => '.',
        'thousands_separator' => ',',
        'rate' => '',
    ],

    'UYU' => [
        'name' => 'Peso Uruguayo',
        'code' => 858,
        'precision' => 2,
        'subunit' => 100,
        'symbol' => '$',
        'symbol_first' => true,
        'decimal_mark' => ',',
        'thousands_separator' => '.',
        'rate' => '',
    ],

    'UZS' => [
        'name' => 'Uzbekistan Sum',
        'code' => 860,
        'precision' => 2,
        'subunit' => 100,
        'symbol' => null,
        'symbol_first' => false,
        'decimal_mark' => '.',
        'thousands_separator' => ',',
        'rate' => '',
    ],

    'VEF' => [
        'name' => 'Bolivar',
        'code' => 937,
        'precision' => 2,
        'subunit' => 100,
        'symbol' => 'Bs F',
        'symbol_first' => true,
        'decimal_mark' => ',',
        'thousands_separator' => '.',
        'rate' => '',
    ],

    'VND' => [
        'name' => 'Dong',
        'code' => 704,
        'precision' => 0,
        'subunit' => 1,
        'symbol' => '₫',
        'symbol_first' => true,
        'decimal_mark' => ',',
        'thousands_separator' => '.',
        'rate' => '',
    ],

    'VUV' => [
        'name' => 'Vatu',
        'code' => 548,
        'precision' => 0,
        'subunit' => 1,
        'symbol' => 'Vt',
        'symbol_first' => true,
        'decimal_mark' => '.',
        'thousands_separator' => ',',
        'rate' => '',
    ],

    'WST' => [
        'name' => 'Tala',
        'code' => 882,
        'precision' => 2,
        'subunit' => 100,
        'symbol' => 'T',
        'symbol_first' => false,
        'decimal_mark' => '.',
        'thousands_separator' => ',',
        'rate' => '',
    ],

    'XAF' => [
        'name' => 'CFA Franc BEAC',
        'code' => 950,
        'precision' => 0,
        'subunit' => 1,
        'symbol' => 'Fr',
        'symbol_first' => false,
        'decimal_mark' => '.',
        'thousands_separator' => ',',
        'rate' => '',
    ],

    'XAG' => [
        'name' => 'Silver',
        'code' => 961,
        'precision' => 0,
        'subunit' => 1,
        'symbol' => 'oz t',
        'symbol_first' => false,
        'decimal_mark' => '.',
        'thousands_separator' => ',',
        'rate' => '',
    ],

    'XAU' => [
        'name' => 'Gold',
        'code' => 959,
        'precision' => 0,
        'subunit' => 1,
        'symbol' => 'oz t',
        'symbol_first' => false,
        'decimal_mark' => '.',
        'thousands_separator' => ',',
        'rate' => '',
    ],

    'XCD' => [
        'name' => 'East Caribbean Dollar',
        'code' => 951,
        'precision' => 2,
        'subunit' => 100,
        'symbol' => '$',
        'symbol_first' => true,
        'decimal_mark' => '.',
        'thousands_separator' => ',',
        'rate' => '',
    ],

    'XDR' => [
        'name' => 'SDR (Special Drawing Right)',
        'code' => 960,
        'precision' => 0,
        'subunit' => 1,
        'symbol' => 'SDR',
        'symbol_first' => false,
        'decimal_mark' => '.',
        'thousands_separator' => ',',
        'rate' => '',
    ],

    'XOF' => [
        'name' => 'CFA Franc BCEAO',
        'code' => 952,
        'precision' => 0,
        'subunit' => 1,
        'symbol' => 'Fr',
        'symbol_first' => false,
        'decimal_mark' => '.',
        'thousands_separator' => ',',
        'rate' => '',
    ],

    'XPF' => [
        'name' => 'CFP Franc',
        'code' => 953,
        'precision' => 0,
        'subunit' => 1,
        'symbol' => 'Fr',
        'symbol_first' => false,
        'decimal_mark' => '.',
        'thousands_separator' => ',',
        'rate' => '',
    ],

    'YER' => [
        'name' => 'Yemeni Rial',
        'code' => 886,
        'precision' => 2,
        'subunit' => 100,
        'symbol' => '﷼',
        'symbol_first' => false,
        'decimal_mark' => '.',
        'thousands_separator' => ',',
        'rate' => '',
    ],

    'ZAR' => [
        'name' => 'Rand',
        'code' => 710,
        'precision' => 2,
        'subunit' => 100,
        'symbol' => 'R',
        'symbol_first' => true,
        'decimal_mark' => '.',
        'thousands_separator' => ',',
        'rate' => '',
    ],

    'ZMW' => [
        'name' => 'Zambian Kwacha',
        'code' => 967,
        'precision' => 2,
        'subunit' => 100,
        'symbol' => 'ZK',
        'symbol_first' => false,
        'decimal_mark' => '.',
        'thousands_separator' => ',',
        'rate' => '',
    ],

    'ZWL' => [
        'name' => 'Zimbabwe Dollar',
        'code' => 932,
        'precision' => 2,
        'subunit' => 100,
        'symbol' => '$',
        'symbol_first' => true,
        'decimal_mark' => '.',
        'thousands_separator' => ',',
        'rate' => '',
    ],
];
